default: &default
  adapter: postgresql 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: meetup_development

test:
  <<: *default
  database: meetup_test

production:
  <<: *default
  database: meetup_production  